//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace BLXml.models.AirBL
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AirwayBillMessage
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AirwayBill", typeof(AirwayBillMessageAirwayBill), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("MessageInfo", typeof(AirwayBillMessageMessageInfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBill
    {

        private string memberCodeField;

        private string hAWBnumberField;

        private string mAWBnumberField;

        private string agentIATACodeField;

        private string airportOfLoadingField;

        private string airportOfLoadingNameField;

        private string flightNoLoadingField;

        private string flightCarrierField;

        private string eTDLoadingField;

        private string airportVia1Field;

        private string airportVia1NameField;

        private string flightNoVia1Field;

        private string via1CarrierField;

        private string eTDVia1Field;

        private string airportVia2Field;

        private string airportVia2NameField;

        private string flightNoVia2Field;

        private string via2CarrierField;

        private string eTDVia2Field;

        private string airportVia3Field;

        private string airportVia3NameField;

        private string flightNoVia3Field;

        private string via3CarrierField;

        private string eTDVia3Field;

        private string airportOfDischargeField;

        private string airportOfDischargeNameField;

        private string eTADischargeField;

        private string placeOfReceiptField;

        private string placeOfDeliveryField;

        private string placeOfDeliveryCountryField;

        private string paymentTerm_MasterField;

        private string paymentTerm_HouseField;

        private string incoTermsField;

        private string bookingReferencesField;

        private AirwayBillMessageAirwayBillPartiesParty[] partiesField;

        private AirwayBillMessageAirwayBillCommoditiesCommodity[] commoditiesField;

        private string actionField;

        private string aWBSeqField;

        private string bookingNoField;

        private string movementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HAWBnumber
        {
            get
            {
                return this.hAWBnumberField;
            }
            set
            {
                this.hAWBnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAWBnumber
        {
            get
            {
                return this.mAWBnumberField;
            }
            set
            {
                this.mAWBnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AgentIATACode
        {
            get
            {
                return this.agentIATACodeField;
            }
            set
            {
                this.agentIATACodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportOfLoading
        {
            get
            {
                return this.airportOfLoadingField;
            }
            set
            {
                this.airportOfLoadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportOfLoadingName
        {
            get
            {
                return this.airportOfLoadingNameField;
            }
            set
            {
                this.airportOfLoadingNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlightNoLoading
        {
            get
            {
                return this.flightNoLoadingField;
            }
            set
            {
                this.flightNoLoadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlightCarrier
        {
            get
            {
                return this.flightCarrierField;
            }
            set
            {
                this.flightCarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETDLoading
        {
            get
            {
                return this.eTDLoadingField;
            }
            set
            {
                this.eTDLoadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia1
        {
            get
            {
                return this.airportVia1Field;
            }
            set
            {
                this.airportVia1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia1Name
        {
            get
            {
                return this.airportVia1NameField;
            }
            set
            {
                this.airportVia1NameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlightNoVia1
        {
            get
            {
                return this.flightNoVia1Field;
            }
            set
            {
                this.flightNoVia1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Via1Carrier
        {
            get
            {
                return this.via1CarrierField;
            }
            set
            {
                this.via1CarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETDVia1
        {
            get
            {
                return this.eTDVia1Field;
            }
            set
            {
                this.eTDVia1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia2
        {
            get
            {
                return this.airportVia2Field;
            }
            set
            {
                this.airportVia2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia2Name
        {
            get
            {
                return this.airportVia2NameField;
            }
            set
            {
                this.airportVia2NameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlightNoVia2
        {
            get
            {
                return this.flightNoVia2Field;
            }
            set
            {
                this.flightNoVia2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Via2Carrier
        {
            get
            {
                return this.via2CarrierField;
            }
            set
            {
                this.via2CarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETDVia2
        {
            get
            {
                return this.eTDVia2Field;
            }
            set
            {
                this.eTDVia2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia3
        {
            get
            {
                return this.airportVia3Field;
            }
            set
            {
                this.airportVia3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportVia3Name
        {
            get
            {
                return this.airportVia3NameField;
            }
            set
            {
                this.airportVia3NameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlightNoVia3
        {
            get
            {
                return this.flightNoVia3Field;
            }
            set
            {
                this.flightNoVia3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Via3Carrier
        {
            get
            {
                return this.via3CarrierField;
            }
            set
            {
                this.via3CarrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETDVia3
        {
            get
            {
                return this.eTDVia3Field;
            }
            set
            {
                this.eTDVia3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportOfDischarge
        {
            get
            {
                return this.airportOfDischargeField;
            }
            set
            {
                this.airportOfDischargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AirportOfDischargeName
        {
            get
            {
                return this.airportOfDischargeNameField;
            }
            set
            {
                this.airportOfDischargeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETADischarge
        {
            get
            {
                return this.eTADischargeField;
            }
            set
            {
                this.eTADischargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlaceOfReceipt
        {
            get
            {
                return this.placeOfReceiptField;
            }
            set
            {
                this.placeOfReceiptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlaceOfDelivery
        {
            get
            {
                return this.placeOfDeliveryField;
            }
            set
            {
                this.placeOfDeliveryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlaceOfDeliveryCountry
        {
            get
            {
                return this.placeOfDeliveryCountryField;
            }
            set
            {
                this.placeOfDeliveryCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentTerm_Master
        {
            get
            {
                return this.paymentTerm_MasterField;
            }
            set
            {
                this.paymentTerm_MasterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentTerm_House
        {
            get
            {
                return this.paymentTerm_HouseField;
            }
            set
            {
                this.paymentTerm_HouseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IncoTerms
        {
            get
            {
                return this.incoTermsField;
            }
            set
            {
                this.incoTermsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BookingReferences
        {
            get
            {
                return this.bookingReferencesField;
            }
            set
            {
                this.bookingReferencesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Party", typeof(AirwayBillMessageAirwayBillPartiesParty), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public AirwayBillMessageAirwayBillPartiesParty[] Parties
        {
            get
            {
                return this.partiesField;
            }
            set
            {
                this.partiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Commodity", typeof(AirwayBillMessageAirwayBillCommoditiesCommodity), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public AirwayBillMessageAirwayBillCommoditiesCommodity[] Commodities
        {
            get
            {
                return this.commoditiesField;
            }
            set
            {
                this.commoditiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AWBSeq
        {
            get
            {
                return this.aWBSeqField;
            }
            set
            {
                this.aWBSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingNo
        {
            get
            {
                return this.bookingNoField;
            }
            set
            {
                this.bookingNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Movement
        {
            get
            {
                return this.movementField;
            }
            set
            {
                this.movementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillPartiesParty
    {

        private string partyTypeField;

        private string companyCodeField;

        private string companyNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartyType
        {
            get
            {
                return this.partyTypeField;
            }
            set
            {
                this.partyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodity
    {

        private AirwayBillMessageAirwayBillCommoditiesCommodityMarksNumbersMarksNumber[] marksNumbersField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCargoDescriptionsCargoDescription[] cargoDescriptionsField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommColli[] commColliField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementActual[] commMeasurementActualField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementCargeable[] commMeasurementCargeableField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightActual[] commWeightActualField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightCargeable[] commWeightCargeableField;

        private AirwayBillMessageAirwayBillCommoditiesCommodityCommHandlingHandlingInformation[] commHandlingField;

        private string itemSeqField;

        private string commodityCodeField;

        private string purchaseOrderField;

        private string itemNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MarksNumber", typeof(AirwayBillMessageAirwayBillCommoditiesCommodityMarksNumbersMarksNumber), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityMarksNumbersMarksNumber[] MarksNumbers
        {
            get
            {
                return this.marksNumbersField;
            }
            set
            {
                this.marksNumbersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CargoDescription", typeof(AirwayBillMessageAirwayBillCommoditiesCommodityCargoDescriptionsCargoDescription), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCargoDescriptionsCargoDescription[] CargoDescriptions
        {
            get
            {
                return this.cargoDescriptionsField;
            }
            set
            {
                this.cargoDescriptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommColli", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommColli[] CommColli
        {
            get
            {
                return this.commColliField;
            }
            set
            {
                this.commColliField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommMeasurementActual", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementActual[] CommMeasurementActual
        {
            get
            {
                return this.commMeasurementActualField;
            }
            set
            {
                this.commMeasurementActualField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommMeasurementCargeable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementCargeable[] CommMeasurementCargeable
        {
            get
            {
                return this.commMeasurementCargeableField;
            }
            set
            {
                this.commMeasurementCargeableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommWeightActual", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightActual[] CommWeightActual
        {
            get
            {
                return this.commWeightActualField;
            }
            set
            {
                this.commWeightActualField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommWeightCargeable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightCargeable[] CommWeightCargeable
        {
            get
            {
                return this.commWeightCargeableField;
            }
            set
            {
                this.commWeightCargeableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HandlingInformation", typeof(AirwayBillMessageAirwayBillCommoditiesCommodityCommHandlingHandlingInformation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AirwayBillMessageAirwayBillCommoditiesCommodityCommHandlingHandlingInformation[] CommHandling
        {
            get
            {
                return this.commHandlingField;
            }
            set
            {
                this.commHandlingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemSeq
        {
            get
            {
                return this.itemSeqField;
            }
            set
            {
                this.itemSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }
            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PurchaseOrder
        {
            get
            {
                return this.purchaseOrderField;
            }
            set
            {
                this.purchaseOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityMarksNumbersMarksNumber
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCargoDescriptionsCargoDescription
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommColli
    {

        private string packageTypeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementActual
    {

        private string uOMField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommMeasurementCargeable
    {

        private string uOMField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightActual
    {

        private string uOMField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommWeightCargeable
    {

        private string uOMField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageAirwayBillCommoditiesCommodityCommHandlingHandlingInformation
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AirwayBillMessageMessageInfo
    {

        private string messageSenderField;

        private string messageRecipientField;

        private string messageNumberField;

        private string createdDateTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageSender
        {
            get
            {
                return this.messageSenderField;
            }
            set
            {
                this.messageSenderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageRecipient
        {
            get
            {
                return this.messageRecipientField;
            }
            set
            {
                this.messageRecipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MessageNumber
        {
            get
            {
                return this.messageNumberField;
            }
            set
            {
                this.messageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }
    }
}