//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace BLXml.models.VS
{

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargofe.com/FECL/FECLVesselScheduleMessage.xsd", IsNullable = false)]
    public partial class VesselScheduleMessage
    {

        private VesselScheduleMessageMessageInfo messageInfoField;

        private VesselScheduleMessageVesselScheduleRecord[] vesselScheduleRecordField;

        /// <remarks/>
        public VesselScheduleMessageMessageInfo MessageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VesselScheduleRecord")]
        public VesselScheduleMessageVesselScheduleRecord[] VesselScheduleRecord
        {
            get
            {
                return this.vesselScheduleRecordField;
            }
            set
            {
                this.vesselScheduleRecordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VesselScheduleMessageMessageInfo
    {

        private string messageSenderField;

        private string messageRecipientField;

        private string messageNumberField;

        private System.DateTime createdDateTimeField;

        private bool createdDateTimeFieldSpecified;

        /// <remarks/>
        public string MessageSender
        {
            get
            {
                return this.messageSenderField;
            }
            set
            {
                this.messageSenderField = value;
            }
        }

        /// <remarks/>
        public string MessageRecipient
        {
            get
            {
                return this.messageRecipientField;
            }
            set
            {
                this.messageRecipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string MessageNumber
        {
            get
            {
                return this.messageNumberField;
            }
            set
            {
                this.messageNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified
        {
            get
            {
                return this.createdDateTimeFieldSpecified;
            }
            set
            {
                this.createdDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VesselScheduleMessageVesselScheduleRecord
    {

        private string memberCodeField;

        private string vesselCodeField;

        private string voyageNoField;

        private VesselScheduleMessageVesselScheduleRecordLiner linerField;

        private VesselScheduleMessageVesselScheduleRecordPOL pOLField;

        private VesselScheduleMessageVesselScheduleRecordPOD pODField;

        private string sequenceField;

        private VesselScheduleMessageVesselScheduleRecordAction actionField;

        /// <remarks/>
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        public string VesselCode
        {
            get
            {
                return this.vesselCodeField;
            }
            set
            {
                this.vesselCodeField = value;
            }
        }

        /// <remarks/>
        public string VoyageNo
        {
            get
            {
                return this.voyageNoField;
            }
            set
            {
                this.voyageNoField = value;
            }
        }

        /// <remarks/>
        public VesselScheduleMessageVesselScheduleRecordLiner Liner
        {
            get
            {
                return this.linerField;
            }
            set
            {
                this.linerField = value;
            }
        }

        /// <remarks/>
        public VesselScheduleMessageVesselScheduleRecordPOL POL
        {
            get
            {
                return this.pOLField;
            }
            set
            {
                this.pOLField = value;
            }
        }

        /// <remarks/>
        public VesselScheduleMessageVesselScheduleRecordPOD POD
        {
            get
            {
                return this.pODField;
            }
            set
            {
                this.pODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VesselScheduleMessageVesselScheduleRecordAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VesselScheduleMessageVesselScheduleRecordLiner
    {

        private string sCACField;

        private string linerNameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SCAC
        {
            get
            {
                return this.sCACField;
            }
            set
            {
                this.sCACField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinerName
        {
            get
            {
                return this.linerNameField;
            }
            set
            {
                this.linerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VesselScheduleMessageVesselScheduleRecordPOL
    {

        private System.DateTime onboardDateField;

        private bool onboardDateFieldSpecified;

        private System.DateTime eTDField;

        private System.DateTime aTDField;

        private bool aTDFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime OnboardDate
        {
            get
            {
                return this.onboardDateField;
            }
            set
            {
                this.onboardDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnboardDateSpecified
        {
            get
            {
                return this.onboardDateFieldSpecified;
            }
            set
            {
                this.onboardDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ETD
        {
            get
            {
                return this.eTDField;
            }
            set
            {
                this.eTDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ATD
        {
            get
            {
                return this.aTDField;
            }
            set
            {
                this.aTDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ATDSpecified
        {
            get
            {
                return this.aTDFieldSpecified;
            }
            set
            {
                this.aTDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VesselScheduleMessageVesselScheduleRecordPOD
    {

        private System.DateTime eTAField;

        private bool eTAFieldSpecified;

        private System.DateTime aTAField;

        private bool aTAFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ETA
        {
            get
            {
                return this.eTAField;
            }
            set
            {
                this.eTAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ETASpecified
        {
            get
            {
                return this.eTAFieldSpecified;
            }
            set
            {
                this.eTAFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ATA
        {
            get
            {
                return this.aTAField;
            }
            set
            {
                this.aTAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ATASpecified
        {
            get
            {
                return this.aTAFieldSpecified;
            }
            set
            {
                this.aTAFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum VesselScheduleMessageVesselScheduleRecordAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Replace,
    }
}