//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace BLXml.models.BL
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd", IsNullable = false)]
    public partial class BillLadingMessage
    {

        private BillLadingMessageMessageInfo messageInfoField;

        private BillLadingMessageBillLading[] billLadingField;

        /// <remarks/>
        public BillLadingMessageMessageInfo MessageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BillLading")]
        public BillLadingMessageBillLading[] BillLading
        {
            get
            {
                return this.billLadingField;
            }
            set
            {
                this.billLadingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMessageInfo
    {

        private string messageSenderField;

        private string messageRecipientField;

        private string messageNumberField;

        private System.DateTime createdDateTimeField;

        private bool createdDateTimeFieldSpecified;

        /// <remarks/>
        public string MessageSender
        {
            get
            {
                return this.messageSenderField;
            }
            set
            {
                this.messageSenderField = value;
            }
        }

        /// <remarks/>
        public string MessageRecipient
        {
            get
            {
                return this.messageRecipientField;
            }
            set
            {
                this.messageRecipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string MessageNumber
        {
            get
            {
                return this.messageNumberField;
            }
            set
            {
                this.messageNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified
        {
            get
            {
                return this.createdDateTimeFieldSpecified;
            }
            set
            {
                this.createdDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLading
    {

        private string memberCodeField;

        private string placeOfReceiptField;

        private string placeOfReceipt_NameField;

        private string portOfLoadingField;

        private string portOfLoading_NameField;

        private string portOfDischargeField;

        private string portOfDischarge_NameField;

        private string placeOfDeliveryField;

        private string placeOfDelivery_NameField;

        private string placeOfDeliveryCountryField;

        private System.DateTime eTADestinationField;

        private bool eTADestinationFieldSpecified;

        private paymentTerm paymentTermField;

        private bool paymentTermFieldSpecified;

        private BillLadingMessageBillLadingReference[] memberReferencesField;

        private BillLadingMessageBillLadingOceanBL oceanBLField;

        private string[] remarksField;

        private BillLadingMessageBillLadingVoyageLeg[] voyageLegsField;

        private BillLadingMessageBillLadingParty[] partiesField;

        private BillLadingMessageBillLadingCommodity[] commoditiesField;

        private BillLadingMessageBillLadingAction actionField;

        private string bLSeqField;

        private string bookingNoField;

        private string houseBLNoField;

        private movement movementField;

        private bool movementFieldSpecified;

        private movement secondMovementField;

        private bool secondMovementFieldSpecified;

        private string paymentField;

        private string payAtField;

        private BillLadingMessageBillLadingBLType bLTypeField;

        private bool bLTypeFieldSpecified;

        private bool isBookingField;

        private bool isBookingFieldSpecified;

        private bool isExpressField;

        private bool isExpressFieldSpecified;

        private System.DateTime issueDateField;

        private string issuePlaceField;

        /// <remarks/>
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfReceipt
        {
            get
            {
                return this.placeOfReceiptField;
            }
            set
            {
                this.placeOfReceiptField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfReceipt_Name
        {
            get
            {
                return this.placeOfReceipt_NameField;
            }
            set
            {
                this.placeOfReceipt_NameField = value;
            }
        }

        /// <remarks/>
        public string PortOfLoading
        {
            get
            {
                return this.portOfLoadingField;
            }
            set
            {
                this.portOfLoadingField = value;
            }
        }

        /// <remarks/>
        public string PortOfLoading_Name
        {
            get
            {
                return this.portOfLoading_NameField;
            }
            set
            {
                this.portOfLoading_NameField = value;
            }
        }

        /// <remarks/>
        public string PortOfDischarge
        {
            get
            {
                return this.portOfDischargeField;
            }
            set
            {
                this.portOfDischargeField = value;
            }
        }

        /// <remarks/>
        public string PortOfDischarge_Name
        {
            get
            {
                return this.portOfDischarge_NameField;
            }
            set
            {
                this.portOfDischarge_NameField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfDelivery
        {
            get
            {
                return this.placeOfDeliveryField;
            }
            set
            {
                this.placeOfDeliveryField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfDelivery_Name
        {
            get
            {
                return this.placeOfDelivery_NameField;
            }
            set
            {
                this.placeOfDelivery_NameField = value;
            }
        }

        /// <remarks/>
        public string PlaceOfDeliveryCountry
        {
            get
            {
                return this.placeOfDeliveryCountryField;
            }
            set
            {
                this.placeOfDeliveryCountryField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ETADestination
        {
            get
            {
                return this.eTADestinationField;
            }
            set
            {
                this.eTADestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ETADestinationSpecified
        {
            get
            {
                return this.eTADestinationFieldSpecified;
            }
            set
            {
                this.eTADestinationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public paymentTerm PaymentTerm
        {
            get
            {
                return this.paymentTermField;
            }
            set
            {
                this.paymentTermField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentTermSpecified
        {
            get
            {
                return this.paymentTermFieldSpecified;
            }
            set
            {
                this.paymentTermFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference")]
        public BillLadingMessageBillLadingReference[] MemberReferences
        {
            get
            {
                return this.memberReferencesField;
            }
            set
            {
                this.memberReferencesField = value;
            }
        }

        /// <remarks/>
        public BillLadingMessageBillLadingOceanBL OceanBL
        {
            get
            {
                return this.oceanBLField;
            }
            set
            {
                this.oceanBLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Remark", IsNullable = false)]
        public string[] Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("VoyageLeg", IsNullable = false)]
        public BillLadingMessageBillLadingVoyageLeg[] VoyageLegs
        {
            get
            {
                return this.voyageLegsField;
            }
            set
            {
                this.voyageLegsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Party", IsNullable = false)]
        public BillLadingMessageBillLadingParty[] Parties
        {
            get
            {
                return this.partiesField;
            }
            set
            {
                this.partiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Commodity", IsNullable = false)]
        public BillLadingMessageBillLadingCommodity[] Commodities
        {
            get
            {
                return this.commoditiesField;
            }
            set
            {
                this.commoditiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BillLadingMessageBillLadingAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string BLSeq
        {
            get
            {
                return this.bLSeqField;
            }
            set
            {
                this.bLSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingNo
        {
            get
            {
                return this.bookingNoField;
            }
            set
            {
                this.bookingNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseBLNo
        {
            get
            {
                return this.houseBLNoField;
            }
            set
            {
                this.houseBLNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public movement Movement
        {
            get
            {
                return this.movementField;
            }
            set
            {
                this.movementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MovementSpecified
        {
            get
            {
                return this.movementFieldSpecified;
            }
            set
            {
                this.movementFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public movement SecondMovement
        {
            get
            {
                return this.secondMovementField;
            }
            set
            {
                this.secondMovementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondMovementSpecified
        {
            get
            {
                return this.secondMovementFieldSpecified;
            }
            set
            {
                this.secondMovementFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Payment
        {
            get
            {
                return this.paymentField;
            }
            set
            {
                this.paymentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PayAt
        {
            get
            {
                return this.payAtField;
            }
            set
            {
                this.payAtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BillLadingMessageBillLadingBLType BLType
        {
            get
            {
                return this.bLTypeField;
            }
            set
            {
                this.bLTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BLTypeSpecified
        {
            get
            {
                return this.bLTypeFieldSpecified;
            }
            set
            {
                this.bLTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsBooking
        {
            get
            {
                return this.isBookingField;
            }
            set
            {
                this.isBookingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBookingSpecified
        {
            get
            {
                return this.isBookingFieldSpecified;
            }
            set
            {
                this.isBookingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsExpress
        {
            get
            {
                return this.isExpressField;
            }
            set
            {
                this.isExpressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsExpressSpecified
        {
            get
            {
                return this.isExpressFieldSpecified;
            }
            set
            {
                this.isExpressFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime issueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string issuePlace
        {
            get
            {
                return this.issuePlaceField;
            }
            set
            {
                this.issuePlaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum paymentTerm
    {

        /// <remarks/>
        CFR,

        /// <remarks/>
        CIF,

        /// <remarks/>
        CIP,

        /// <remarks/>
        CPT,

        /// <remarks/>
        DAF,

        /// <remarks/>
        DDP,

        /// <remarks/>
        DDU,

        /// <remarks/>
        DEQ,

        /// <remarks/>
        DES,

        /// <remarks/>
        EXW,

        /// <remarks/>
        FAS,

        /// <remarks/>
        FCA,

        /// <remarks/>
        FOB,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingReference
    {

        private referenceType refTypeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public referenceType refType
        {
            get
            {
                return this.refTypeField;
            }
            set
            {
                this.refTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum referenceType
    {

        /// <remarks/>
        JobNumber,

        /// <remarks/>
        ShipperRefno,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingOceanBL
    {

        private BillLadingMessageBillLadingOceanBLCarrier carrierField;

        private string oceanBLNoField;

        private string oceanBLPORField;

        private string oceanBLPOR_NameField;

        private string oceanBLPOLField;

        private string oceanBLPOL_NameField;

        private string oceanBLPODField;

        private string oceanBLPOD_NameField;

        private string oceanBLDELField;

        private string oceanBLDEL_NameField;

        private movement oceanBLMovementField;

        private bool oceanBLMovementFieldSpecified;

        private string oceanPaymentField;

        /// <remarks/>
        public BillLadingMessageBillLadingOceanBLCarrier Carrier
        {
            get
            {
                return this.carrierField;
            }
            set
            {
                this.carrierField = value;
            }
        }

        /// <remarks/>
        public string OceanBLNo
        {
            get
            {
                return this.oceanBLNoField;
            }
            set
            {
                this.oceanBLNoField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOR
        {
            get
            {
                return this.oceanBLPORField;
            }
            set
            {
                this.oceanBLPORField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOR_Name
        {
            get
            {
                return this.oceanBLPOR_NameField;
            }
            set
            {
                this.oceanBLPOR_NameField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOL
        {
            get
            {
                return this.oceanBLPOLField;
            }
            set
            {
                this.oceanBLPOLField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOL_Name
        {
            get
            {
                return this.oceanBLPOL_NameField;
            }
            set
            {
                this.oceanBLPOL_NameField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOD
        {
            get
            {
                return this.oceanBLPODField;
            }
            set
            {
                this.oceanBLPODField = value;
            }
        }

        /// <remarks/>
        public string OceanBLPOD_Name
        {
            get
            {
                return this.oceanBLPOD_NameField;
            }
            set
            {
                this.oceanBLPOD_NameField = value;
            }
        }

        /// <remarks/>
        public string OceanBLDEL
        {
            get
            {
                return this.oceanBLDELField;
            }
            set
            {
                this.oceanBLDELField = value;
            }
        }

        /// <remarks/>
        public string OceanBLDEL_Name
        {
            get
            {
                return this.oceanBLDEL_NameField;
            }
            set
            {
                this.oceanBLDEL_NameField = value;
            }
        }

        /// <remarks/>
        public movement OceanBLMovement
        {
            get
            {
                return this.oceanBLMovementField;
            }
            set
            {
                this.oceanBLMovementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OceanBLMovementSpecified
        {
            get
            {
                return this.oceanBLMovementFieldSpecified;
            }
            set
            {
                this.oceanBLMovementFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string OceanPayment
        {
            get
            {
                return this.oceanPaymentField;
            }
            set
            {
                this.oceanPaymentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingOceanBLCarrier
    {

        private string sCACField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SCAC
        {
            get
            {
                return this.sCACField;
            }
            set
            {
                this.sCACField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum movement
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CFS/CFS")]
        CFSCFS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CFS/CY")]
        CFSCY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CY/CFS")]
        CYCFS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CY/CY")]
        CYCY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RO/RO")]
        RORO,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingVoyageLeg
    {

        private string linerCodeField;

        private string linerCode_NameField;

        private string vesselCodeField;

        private string voyageNumberField;

        private string loadPortField;

        private string loadPort_NameField;

        private string dischargePortField;

        private string dischargePort_NameField;

        private string voyLegSeqField;

        private bool printOnBLField;

        public BillLadingMessageBillLadingVoyageLeg()
        {
            this.printOnBLField = false;
        }

        /// <remarks/>
        public string LinerCode
        {
            get
            {
                return this.linerCodeField;
            }
            set
            {
                this.linerCodeField = value;
            }
        }

        /// <remarks/>
        public string LinerCode_Name
        {
            get
            {
                return this.linerCode_NameField;
            }
            set
            {
                this.linerCode_NameField = value;
            }
        }

        /// <remarks/>
        public string VesselCode
        {
            get
            {
                return this.vesselCodeField;
            }
            set
            {
                this.vesselCodeField = value;
            }
        }

        /// <remarks/>
        public string VoyageNumber
        {
            get
            {
                return this.voyageNumberField;
            }
            set
            {
                this.voyageNumberField = value;
            }
        }

        /// <remarks/>
        public string LoadPort
        {
            get
            {
                return this.loadPortField;
            }
            set
            {
                this.loadPortField = value;
            }
        }

        /// <remarks/>
        public string LoadPort_Name
        {
            get
            {
                return this.loadPort_NameField;
            }
            set
            {
                this.loadPort_NameField = value;
            }
        }

        /// <remarks/>
        public string DischargePort
        {
            get
            {
                return this.dischargePortField;
            }
            set
            {
                this.dischargePortField = value;
            }
        }

        /// <remarks/>
        public string DischargePort_Name
        {
            get
            {
                return this.dischargePort_NameField;
            }
            set
            {
                this.dischargePort_NameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string VoyLegSeq
        {
            get
            {
                return this.voyLegSeqField;
            }
            set
            {
                this.voyLegSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool PrintOnBL
        {
            get
            {
                return this.printOnBLField;
            }
            set
            {
                this.printOnBLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingParty
    {

        private string nameField;

        private string addressLine1Field;

        private string addressLine2Field;

        private string addressLine3Field;

        private string addressLine4Field;

        private string cityField;

        private string zipCodeField;

        private country countryField;

        private bool countryFieldSpecified;

        private string contactPersonField;

        private string departmentField;

        private string telephoneNumberField;

        private string faxNumberField;

        private companyType companyTypeField;

        private string companyCodeField;

        private string addressSeqNoField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySpecified
        {
            get
            {
                return this.countryFieldSpecified;
            }
            set
            {
                this.countryFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        public string TelephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public companyType CompanyType
        {
            get
            {
                return this.companyTypeField;
            }
            set
            {
                this.companyTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string AddressSeqNo
        {
            get
            {
                return this.addressSeqNoField;
            }
            set
            {
                this.addressSeqNoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum country
    {

        /// <remarks/>
        DZ,

        /// <remarks/>
        AO,

        /// <remarks/>
        AG,

        /// <remarks/>
        AR,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BR,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        KY,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        CO,

        /// <remarks/>
        CG,

        /// <remarks/>
        CR,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        CY,

        /// <remarks/>
        CZ,

        /// <remarks/>
        DK,

        /// <remarks/>
        DJ,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EG,

        /// <remarks/>
        SV,

        /// <remarks/>
        ER,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        FJ,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        DE,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GR,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GN,

        /// <remarks/>
        GY,

        /// <remarks/>
        HN,

        /// <remarks/>
        HU,

        /// <remarks/>
        IS,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IE,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        CI,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        KE,

        /// <remarks/>
        KW,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LU,

        /// <remarks/>
        MO,

        /// <remarks/>
        MG,

        /// <remarks/>
        MY,

        /// <remarks/>
        MT,

        /// <remarks/>
        MR,

        /// <remarks/>
        MU,

        /// <remarks/>
        MX,

        /// <remarks/>
        MC,

        /// <remarks/>
        MA,

        /// <remarks/>
        MZ,

        /// <remarks/>
        NA,

        /// <remarks/>
        NL,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        NI,

        /// <remarks/>
        NO,

        /// <remarks/>
        OM,

        /// <remarks/>
        PK,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PH,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        SA,

        /// <remarks/>
        SN,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SI,

        /// <remarks/>
        ZA,

        /// <remarks/>
        KR,

        /// <remarks/>
        ES,

        /// <remarks/>
        LK,

        /// <remarks/>
        SD,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        TW,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TH,

        /// <remarks/>
        TG,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TR,

        /// <remarks/>
        UG,

        /// <remarks/>
        AE,

        /// <remarks/>
        GB,

        /// <remarks/>
        US,

        /// <remarks/>
        UY,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        YE,

        /// <remarks/>
        ZM,

        /// <remarks/>
        BU,

        /// <remarks/>
        HT,

        /// <remarks/>
        IQ,

        /// <remarks/>
        KI,

        /// <remarks/>
        MQ,

        /// <remarks/>
        SB,

        /// <remarks/>
        KP,

        /// <remarks/>
        BB,

        /// <remarks/>
        BT,

        /// <remarks/>
        BO,

        /// <remarks/>
        NP,

        /// <remarks/>
        EC,

        /// <remarks/>
        GE,

        /// <remarks/>
        HK,

        /// <remarks/>
        JO,

        /// <remarks/>
        NG,

        /// <remarks/>
        SY,

        /// <remarks/>
        UA,

        /// <remarks/>
        ZW,

        /// <remarks/>
        YU,

        /// <remarks/>
        MP,

        /// <remarks/>
        RE,

        /// <remarks/>
        MK,

        /// <remarks/>
        AM,

        /// <remarks/>
        GP,

        /// <remarks/>
        GF,

        /// <remarks/>
        LT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum companyType
    {

        /// <remarks/>
        Shipper,

        /// <remarks/>
        Consignee,

        /// <remarks/>
        Agent,

        /// <remarks/>
        Notify1,

        /// <remarks/>
        Notify2,

        /// <remarks/>
        Notify3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodity
    {

        private BillLadingMessageBillLadingCommodityMarksNumber[] marksNumbersField;

        private BillLadingMessageBillLadingCommodityCargoDescriptionsCargoDescription[] cargoDescriptionsField;

        private BillLadingMessageBillLadingCommodityCommPackaging[] commPackagingField;

        private BillLadingMessageBillLadingCommodityCommMeasurement[] commMeasurementField;

        private BillLadingMessageBillLadingCommodityCommWeight[] commWeightField;

        private BillLadingMessageBillLadingCommodityCommContainer[] commContainerField;

        private string itemSeqField;

        private string commodityCodeField;

        private string purchaseOrderField;

        private string itemNumberField;

        private System.DateTime cargoReceivedDateField;

        private bool cargoReceivedDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MarksNumber")]
        public BillLadingMessageBillLadingCommodityMarksNumber[] MarksNumbers
        {
            get
            {
                return this.marksNumbersField;
            }
            set
            {
                this.marksNumbersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CargoDescription", typeof(BillLadingMessageBillLadingCommodityCargoDescriptionsCargoDescription))]
        public BillLadingMessageBillLadingCommodityCargoDescriptionsCargoDescription[] CargoDescriptions
        {
            get
            {
                return this.cargoDescriptionsField;
            }
            set
            {
                this.cargoDescriptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommPackaging", IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommPackaging[] CommPackaging
        {
            get
            {
                return this.commPackagingField;
            }
            set
            {
                this.commPackagingField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type BillLadingMessageBillLadingCommodityCommMeasurement[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='0' attribute on element name='CommMeasurement'.
        [System.Xml.Serialization.XmlElementAttribute("CommMeasurement", IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommMeasurement[] CommMeasurement
        {
            get
            {
                return this.commMeasurementField;
            }
            set
            {
                this.commMeasurementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommWeight", IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommWeight[] CommWeight
        {
            get
            {
                return this.commWeightField;
            }
            set
            {
                this.commWeightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommContainer")]
        public BillLadingMessageBillLadingCommodityCommContainer[] CommContainer
        {
            get
            {
                return this.commContainerField;
            }
            set
            {
                this.commContainerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string ItemSeq
        {
            get
            {
                return this.itemSeqField;
            }
            set
            {
                this.itemSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }
            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PurchaseOrder
        {
            get
            {
                return this.purchaseOrderField;
            }
            set
            {
                this.purchaseOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime CargoReceivedDate
        {
            get
            {
                return this.cargoReceivedDateField;
            }
            set
            {
                this.cargoReceivedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CargoReceivedDateSpecified
        {
            get
            {
                return this.cargoReceivedDateFieldSpecified;
            }
            set
            {
                this.cargoReceivedDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityMarksNumber
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCargoDescriptionsCargoDescription
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommPackaging
    {

        private packageType packageTypeField;

        private bool packageTypeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public packageType PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageTypeSpecified
        {
            get
            {
                return this.packageTypeFieldSpecified;
            }
            set
            {
                this.packageTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum packageType
    {

        /// <remarks/>
        BC,

        /// <remarks/>
        BE,

        /// <remarks/>
        BG,

        /// <remarks/>
        BI,

        /// <remarks/>
        BK,

        /// <remarks/>
        BL,

        /// <remarks/>
        BO,

        /// <remarks/>
        BR,

        /// <remarks/>
        BX,

        /// <remarks/>
        CA,

        /// <remarks/>
        CG,

        /// <remarks/>
        CL,

        /// <remarks/>
        CR,

        /// <remarks/>
        CS,

        /// <remarks/>
        CT,

        /// <remarks/>
        DR,

        /// <remarks/>
        LV,

        /// <remarks/>
        PB,

        /// <remarks/>
        PC,

        /// <remarks/>
        PI,

        /// <remarks/>
        PK,

        /// <remarks/>
        PL,

        /// <remarks/>
        PR,

        /// <remarks/>
        RO,

        /// <remarks/>
        ST,

        /// <remarks/>
        SU,

        /// <remarks/>
        UN,

        /// <remarks/>
        WC,

        /// <remarks/>
        WP,

        /// <remarks/>
        SC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommMeasurement
    {

        private string uOMField;

        private decimal valueField;

        public BillLadingMessageBillLadingCommodityCommMeasurement()
        {
            this.uOMField = "CBM";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommWeight
    {

        private string uOMField;

        private decimal valueField;

        public BillLadingMessageBillLadingCommodityCommWeight()
        {
            this.uOMField = "KG";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommContainer
    {

        private BillLadingMessageBillLadingCommodityCommContainerContainerPackaging containerPackagingField;

        private BillLadingMessageBillLadingCommodityCommContainerContainerMeasurement containerMeasurementField;

        private BillLadingMessageBillLadingCommodityCommContainerContainerWeight containerWeightField;

        private string containerNumberField;

        private containerType containerTypeField;

        private bool containerTypeFieldSpecified;

        private string sealNumberField;

        private movement contMovementField;

        private bool contMovementFieldSpecified;

        public BillLadingMessageBillLadingCommodityCommContainer()
        {
            this.containerNumberField = "N/A";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommContainerContainerPackaging ContainerPackaging
        {
            get
            {
                return this.containerPackagingField;
            }
            set
            {
                this.containerPackagingField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type BillLadingMessageBillLadingCommodityCommContainerContainerMeasurement is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='0' attribute.
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommContainerContainerMeasurement ContainerMeasurement
        {
            get
            {
                return this.containerMeasurementField;
            }
            set
            {
                this.containerMeasurementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BillLadingMessageBillLadingCommodityCommContainerContainerWeight ContainerWeight
        {
            get
            {
                return this.containerWeightField;
            }
            set
            {
                this.containerWeightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("N/A")]
        public string ContainerNumber
        {
            get
            {
                return this.containerNumberField;
            }
            set
            {
                this.containerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public containerType ContainerType
        {
            get
            {
                return this.containerTypeField;
            }
            set
            {
                this.containerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContainerTypeSpecified
        {
            get
            {
                return this.containerTypeFieldSpecified;
            }
            set
            {
                this.containerTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SealNumber
        {
            get
            {
                return this.sealNumberField;
            }
            set
            {
                this.sealNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public movement ContMovement
        {
            get
            {
                return this.contMovementField;
            }
            set
            {
                this.contMovementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContMovementSpecified
        {
            get
            {
                return this.contMovementFieldSpecified;
            }
            set
            {
                this.contMovementFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommContainerContainerPackaging
    {

        private packageType packageTypeField;

        private bool packageTypeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public packageType PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackageTypeSpecified
        {
            get
            {
                return this.packageTypeFieldSpecified;
            }
            set
            {
                this.packageTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommContainerContainerMeasurement
    {

        private string uOMField;

        private decimal valueField;

        public BillLadingMessageBillLadingCommodityCommContainerContainerMeasurement()
        {
            this.uOMField = "CBM";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageBillLadingCommodityCommContainerContainerWeight
    {

        private string uOMField;

        private decimal valueField;

        public BillLadingMessageBillLadingCommodityCommContainerContainerWeight()
        {
            this.uOMField = "KG";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLBillLadingMessage.xsd")]
    public enum containerType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20FR")]
        Item20FR,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20GH")]
        Item20GH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20HC")]
        Item20HC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20OT")]
        Item20OT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20RD")]
        Item20RD,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20RF")]
        Item20RF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20ST")]
        Item20ST,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40FR")]
        Item40FR,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40GH")]
        Item40GH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40HC")]
        Item40HC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40HD")]
        Item40HD,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40HG")]
        Item40HG,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40HR")]
        Item40HR,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40OT")]
        Item40OT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40RD")]
        Item40RD,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40RF")]
        Item40RF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40ST")]
        Item40ST,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45ST")]
        Item45ST,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum BillLadingMessageBillLadingAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Replace,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum BillLadingMessageBillLadingBLType
    {

        /// <remarks/>
        Nomination,

        /// <remarks/>
        Freehand,

        /// <remarks/>
        JointEffort,
    }
}