//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace BLXml.models.CM
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargofe.com/FECL/FECLCompanyMessage.xsd", IsNullable = false)]
    public partial class CompanyMessage
    {

        private CompanyMessageMessageInfo messageInfoField;

        private CompanyMessageCompanyRecord[] companyRecordField;

        /// <remarks/>
        public CompanyMessageMessageInfo MessageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyRecord")]
        public CompanyMessageCompanyRecord[] CompanyRecord
        {
            get
            {
                return this.companyRecordField;
            }
            set
            {
                this.companyRecordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CompanyMessageMessageInfo
    {

        private string messageSenderField;

        private string messageRecipientField;

        private string messageNumberField;

        private System.DateTime createdDateTimeField;

        private bool createdDateTimeFieldSpecified;

        /// <remarks/>
        public string MessageSender
        {
            get
            {
                return this.messageSenderField;
            }
            set
            {
                this.messageSenderField = value;
            }
        }

        /// <remarks/>
        public string MessageRecipient
        {
            get
            {
                return this.messageRecipientField;
            }
            set
            {
                this.messageRecipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string MessageNumber
        {
            get
            {
                return this.messageNumberField;
            }
            set
            {
                this.messageNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified
        {
            get
            {
                return this.createdDateTimeFieldSpecified;
            }
            set
            {
                this.createdDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CompanyMessageCompanyRecord
    {

        private string memberCodeField;

        private string companyCodeField;

        private string companyNameField;

        private bool isShipperField;

        private bool isConsigneeField;

        private bool isAgentField;

        private bool isNotifyField;

        private string equMemberCodeField;

        private CompanyMessageCompanyRecordCompanyContact[] companyContactField;

        private string sequenceField;

        private CompanyMessageCompanyRecordAction actionField;

        public CompanyMessageCompanyRecord()
        {
            this.isShipperField = true;
            this.isConsigneeField = true;
            this.isAgentField = true;
            this.isNotifyField = true;
        }

        /// <remarks/>
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        //[System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsShipper
        {
            get
            {
                return this.isShipperField;
            }
            set
            {
                this.isShipperField = value;
            }
        }

        /// <remarks/>
        //[System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsConsignee
        {
            get
            {
                return this.isConsigneeField;
            }
            set
            {
                this.isConsigneeField = value;
            }
        }

        /// <remarks/>
        //[System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsAgent
        {
            get
            {
                return this.isAgentField;
            }
            set
            {
                this.isAgentField = value;
            }
        }

        /// <remarks/>
        //[System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsNotify
        {
            get
            {
                return this.isNotifyField;
            }
            set
            {
                this.isNotifyField = value;
            }
        }

        /// <remarks/>
        public string equMemberCode
        {
            get
            {
                return this.equMemberCodeField;
            }
            set
            {
                this.equMemberCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyContact")]
        public CompanyMessageCompanyRecordCompanyContact[] CompanyContact
        {
            get
            {
                return this.companyContactField;
            }
            set
            {
                this.companyContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string Sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyMessageCompanyRecordAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CompanyMessageCompanyRecordCompanyContact
    {

        private string contactPersonField;

        private string positionField;

        private string departmentField;

        private string addressLine1Field;

        private string addressLine2Field;

        private string addressLine3Field;

        private string addressLine4Field;

        private string cityField;

        private string zipCodeField;

        private country countryField;

        private bool countryFieldSpecified;

        private string directNumberField;

        private string telephoneNumberField;

        private string faxNumberField;

        private string mobileNumberField;

        private string emailAddressField;

        private string webSiteField;

        private string contactSeqField;

        private CompanyMessageCompanyRecordCompanyContactContactAction contactActionField;

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public country Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountrySpecified
        {
            get
            {
                return this.countryFieldSpecified;
            }
            set
            {
                this.countryFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string DirectNumber
        {
            get
            {
                return this.directNumberField;
            }
            set
            {
                this.directNumberField = value;
            }
        }

        /// <remarks/>
        public string TelephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }

        /// <remarks/>
        public string MobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
            }
        }

        /// <remarks/>
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        public string WebSite
        {
            get
            {
                return this.webSiteField;
            }
            set
            {
                this.webSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string ContactSeq
        {
            get
            {
                return this.contactSeqField;
            }
            set
            {
                this.contactSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyMessageCompanyRecordCompanyContactContactAction ContactAction
        {
            get
            {
                return this.contactActionField;
            }
            set
            {
                this.contactActionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLCompanyMessage.xsd")]
    public enum country
    {

        /// <remarks/>
        DZ,

        /// <remarks/>
        AO,

        /// <remarks/>
        AG,

        /// <remarks/>
        AR,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BR,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        KY,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        CO,

        /// <remarks/>
        CG,

        /// <remarks/>
        CR,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        CY,

        /// <remarks/>
        CZ,

        /// <remarks/>
        DK,

        /// <remarks/>
        DJ,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EG,

        /// <remarks/>
        SV,

        /// <remarks/>
        ER,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        FJ,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        DE,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GR,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GN,

        /// <remarks/>
        GY,

        /// <remarks/>
        HN,

        /// <remarks/>
        HU,

        /// <remarks/>
        IS,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IE,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        CI,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        KE,

        /// <remarks/>
        KW,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LU,

        /// <remarks/>
        MO,

        /// <remarks/>
        MG,

        /// <remarks/>
        MY,

        /// <remarks/>
        MT,

        /// <remarks/>
        MR,

        /// <remarks/>
        MU,

        /// <remarks/>
        MX,

        /// <remarks/>
        MC,

        /// <remarks/>
        MA,

        /// <remarks/>
        MZ,

        /// <remarks/>
        NA,

        /// <remarks/>
        NL,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        NI,

        /// <remarks/>
        NO,

        /// <remarks/>
        OM,

        /// <remarks/>
        PK,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PH,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        SA,

        /// <remarks/>
        SN,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SI,

        /// <remarks/>
        ZA,

        /// <remarks/>
        KR,

        /// <remarks/>
        ES,

        /// <remarks/>
        LK,

        /// <remarks/>
        SD,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        TW,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TH,

        /// <remarks/>
        TG,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TR,

        /// <remarks/>
        UG,

        /// <remarks/>
        AE,

        /// <remarks/>
        GB,

        /// <remarks/>
        US,

        /// <remarks/>
        UY,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        YE,

        /// <remarks/>
        ZM,

        /// <remarks/>
        BU,

        /// <remarks/>
        HT,

        /// <remarks/>
        IQ,

        /// <remarks/>
        KI,

        /// <remarks/>
        MQ,

        /// <remarks/>
        SB,

        /// <remarks/>
        KP,

        /// <remarks/>
        BB,

        /// <remarks/>
        BT,

        /// <remarks/>
        BO,

        /// <remarks/>
        NP,

        /// <remarks/>
        EC,

        /// <remarks/>
        GE,

        /// <remarks/>
        HK,

        /// <remarks/>
        JO,

        /// <remarks/>
        NG,

        /// <remarks/>
        SY,

        /// <remarks/>
        UA,

        /// <remarks/>
        ZW,

        /// <remarks/>
        YU,

        /// <remarks/>
        MP,

        /// <remarks/>
        RE,

        /// <remarks/>
        MK,

        /// <remarks/>
        AM,

        /// <remarks/>
        GP,

        /// <remarks/>
        GF,

        /// <remarks/>
        LT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CompanyMessageCompanyRecordCompanyContactContactAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Replace,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CompanyMessageCompanyRecordAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Replace,
    }
}