//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace BLXml.models.ST
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cargofe.com/FECL/FECLShipmentTrackingMessage.xsd", IsNullable = false)]
    public partial class ShipmentTrackingMessage
    {

        private ShipmentTrackingMessageMessageInfo messageInfoField;

        private ShipmentTrackingMessageShipmentEvents[] shipmentEventsField;

        /// <remarks/>
        public ShipmentTrackingMessageMessageInfo MessageInfo
        {
            get
            {
                return this.messageInfoField;
            }
            set
            {
                this.messageInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentEvents")]
        public ShipmentTrackingMessageShipmentEvents[] ShipmentEvents
        {
            get
            {
                return this.shipmentEventsField;
            }
            set
            {
                this.shipmentEventsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ShipmentTrackingMessageMessageInfo
    {

        private string messageSenderField;

        private string messageRecipientField;

        private string messageNumberField;

        private System.DateTime createdDateTimeField;

        private bool createdDateTimeFieldSpecified;

        /// <remarks/>
        public string MessageSender
        {
            get
            {
                return this.messageSenderField;
            }
            set
            {
                this.messageSenderField = value;
            }
        }

        /// <remarks/>
        public string MessageRecipient
        {
            get
            {
                return this.messageRecipientField;
            }
            set
            {
                this.messageRecipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string MessageNumber
        {
            get
            {
                return this.messageNumberField;
            }
            set
            {
                this.messageNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.createdDateTimeField;
            }
            set
            {
                this.createdDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified
        {
            get
            {
                return this.createdDateTimeFieldSpecified;
            }
            set
            {
                this.createdDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ShipmentTrackingMessageShipmentEvents
    {

        private ShipmentTrackingMessageShipmentEventsShipmentEvent[] shipmentEventField;

        private string memberCodeField;

        private string bookingNumberField;

        private string houseBLNumberField;

        private string containerNumberField;

        private string sTSeqField;

        private ShipmentTrackingMessageShipmentEventsAction actionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShipmentEvent")]
        public ShipmentTrackingMessageShipmentEventsShipmentEvent[] ShipmentEvent
        {
            get
            {
                return this.shipmentEventField;
            }
            set
            {
                this.shipmentEventField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingNumber
        {
            get
            {
                return this.bookingNumberField;
            }
            set
            {
                this.bookingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseBLNumber
        {
            get
            {
                return this.houseBLNumberField;
            }
            set
            {
                this.houseBLNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContainerNumber
        {
            get
            {
                return this.containerNumberField;
            }
            set
            {
                this.containerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string STSeq
        {
            get
            {
                return this.sTSeqField;
            }
            set
            {
                this.sTSeqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ShipmentTrackingMessageShipmentEventsAction Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ShipmentTrackingMessageShipmentEventsShipmentEvent
    {

        private string freeDaysField;

        private ShipmentTrackingMessageShipmentEventsShipmentEventVesselVoyage vesselVoyageField;

        private ShipmentTrackingMessageShipmentEventsShipmentEventDeliveredTo deliveredToField;

        private eventCode eventCodeField;

        private System.DateTime eventDateTimeField;

        private string locationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FreeDays
        {
            get
            {
                return this.freeDaysField;
            }
            set
            {
                this.freeDaysField = value;
            }
        }

        /// <remarks/>
        public ShipmentTrackingMessageShipmentEventsShipmentEventVesselVoyage VesselVoyage
        {
            get
            {
                return this.vesselVoyageField;
            }
            set
            {
                this.vesselVoyageField = value;
            }
        }

        /// <remarks/>
        public ShipmentTrackingMessageShipmentEventsShipmentEventDeliveredTo DeliveredTo
        {
            get
            {
                return this.deliveredToField;
            }
            set
            {
                this.deliveredToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public eventCode EventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime
        {
            get
            {
                return this.eventDateTimeField;
            }
            set
            {
                this.eventDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ShipmentTrackingMessageShipmentEventsShipmentEventVesselVoyage
    {

        private string memberCodeField;

        private string vesselCodeField;

        private string voyageNumberField;

        private string linerCodeField;

        private string linerCode_NameField;

        private string fromPortField;

        private string fromPort_NameField;

        private string toPortField;

        private string toPort_NameField;

        private System.DateTime eTDField;

        private bool eTDFieldSpecified;

        private System.DateTime eTAField;

        private bool eTAFieldSpecified;

        private string vesvoynoField;

        /// <remarks/>
        public string MemberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }

        /// <remarks/>
        public string VesselCode
        {
            get
            {
                return this.vesselCodeField;
            }
            set
            {
                this.vesselCodeField = value;
            }
        }

        /// <remarks/>
        public string VoyageNumber
        {
            get
            {
                return this.voyageNumberField;
            }
            set
            {
                this.voyageNumberField = value;
            }
        }

        /// <remarks/>
        public string LinerCode
        {
            get
            {
                return this.linerCodeField;
            }
            set
            {
                this.linerCodeField = value;
            }
        }

        /// <remarks/>
        public string LinerCode_Name
        {
            get
            {
                return this.linerCode_NameField;
            }
            set
            {
                this.linerCode_NameField = value;
            }
        }

        /// <remarks/>
        public string FromPort
        {
            get
            {
                return this.fromPortField;
            }
            set
            {
                this.fromPortField = value;
            }
        }

        /// <remarks/>
        public string FromPort_Name
        {
            get
            {
                return this.fromPort_NameField;
            }
            set
            {
                this.fromPort_NameField = value;
            }
        }

        /// <remarks/>
        public string ToPort
        {
            get
            {
                return this.toPortField;
            }
            set
            {
                this.toPortField = value;
            }
        }

        /// <remarks/>
        public string ToPort_Name
        {
            get
            {
                return this.toPort_NameField;
            }
            set
            {
                this.toPort_NameField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ETD
        {
            get
            {
                return this.eTDField;
            }
            set
            {
                this.eTDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ETDSpecified
        {
            get
            {
                return this.eTDFieldSpecified;
            }
            set
            {
                this.eTDFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime ETA
        {
            get
            {
                return this.eTAField;
            }
            set
            {
                this.eTAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ETASpecified
        {
            get
            {
                return this.eTAFieldSpecified;
            }
            set
            {
                this.eTAFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Vesvoyno
        {
            get
            {
                return this.vesvoynoField;
            }
            set
            {
                this.vesvoynoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ShipmentTrackingMessageShipmentEventsShipmentEventDeliveredTo
    {

        private string nameField;

        private string contactPersonField;

        private string addressLine1Field;

        private string addressLine2Field;

        private string addressLine3Field;

        private string addressLine4Field;

        private string cityField;

        private string countryField;

        private string telephoneNumberField;

        private string faxNumberField;

        private string emailField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }

        /// <remarks/>
        public string AddressLine4
        {
            get
            {
                return this.addressLine4Field;
            }
            set
            {
                this.addressLine4Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string TelephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cargofe.com/FECL/FECLShipmentTrackingMessage.xsd")]
    public enum eventCode
    {

        /// <remarks/>
        ACW,

        /// <remarks/>
        ARW,

        /// <remarks/>
        ASC,

        /// <remarks/>
        BKG,

        /// <remarks/>
        CLR,

        /// <remarks/>
        DLG,

        /// <remarks/>
        DLY,

        /// <remarks/>
        ECC,

        /// <remarks/>
        ETA,

        /// <remarks/>
        ONB,

        /// <remarks/>
        RCV,

        /// <remarks/>
        TCW,

        /// <remarks/>
        TSP,

        /// <remarks/>
        TSW,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ShipmentTrackingMessageShipmentEventsAction
    {

        /// <remarks/>
        Create,

        /// <remarks/>
        Amend,

        /// <remarks/>
        Delete,

        /// <remarks/>
        Replace,
    }
}