//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace BLXml.models.MexicoBL
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MessageBLInfo
    {

        private string processIDField;

        private MessageBLInfoVslVoy[] vslVoyField;

        private MessageBLInfoOrdersOrder[] ordersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessID
        {
            get
            {
                return this.processIDField;
            }
            set
            {
                this.processIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VslVoy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBLInfoVslVoy[] VslVoy
        {
            get
            {
                return this.vslVoyField;
            }
            set
            {
                this.vslVoyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Order", typeof(MessageBLInfoOrdersOrder), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBLInfoOrdersOrder[] Orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageBLInfoVslVoy
    {

        private string carrierField;

        private string vslNameField;

        private string voygaeField;

        private string oriCountryField;

        private string pOLField;

        private string pODField;

        private string finalDestinationField;

        private string tSPortField;

        private string tSPortDateField;

        private string cutOffField;

        private string eTDField;

        private string eTAField;

        private string trafficField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Carrier
        {
            get
            {
                return this.carrierField;
            }
            set
            {
                this.carrierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VslName
        {
            get
            {
                return this.vslNameField;
            }
            set
            {
                this.vslNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voygae
        {
            get
            {
                return this.voygaeField;
            }
            set
            {
                this.voygaeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriCountry
        {
            get
            {
                return this.oriCountryField;
            }
            set
            {
                this.oriCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POL
        {
            get
            {
                return this.pOLField;
            }
            set
            {
                this.pOLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POD
        {
            get
            {
                return this.pODField;
            }
            set
            {
                this.pODField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FinalDestination
        {
            get
            {
                return this.finalDestinationField;
            }
            set
            {
                this.finalDestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TSPort
        {
            get
            {
                return this.tSPortField;
            }
            set
            {
                this.tSPortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TSPortDate
        {
            get
            {
                return this.tSPortDateField;
            }
            set
            {
                this.tSPortDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CutOff
        {
            get
            {
                return this.cutOffField;
            }
            set
            {
                this.cutOffField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETD
        {
            get
            {
                return this.eTDField;
            }
            set
            {
                this.eTDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ETA
        {
            get
            {
                return this.eTAField;
            }
            set
            {
                this.eTAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Traffic
        {
            get
            {
                return this.trafficField;
            }
            set
            {
                this.trafficField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageBLInfoOrdersOrder
    {

        private string pOIDField;

        private string poField;

        private string styleNoField;

        private string pOSupplierField;

        private string oLDPOField;

        private string hBLNumberField;

        private string documentTypeField;

        private string shipperField;

        private string shipperCountryField;

        private string shipperAddressField;

        private string shipperPhoneNumberField;

        private string notifyPartyField;

        private string mBLNumberField;

        private string serviceContractField;

        private string containerNumberField;

        private string containerTypeField;

        private string carrierSealField;

        private string shipperSealField;

        private string loadTypeField;

        private string intertraficInspectionField;

        private string inspectionInField;

        private string inspectionSupplierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POID
        {
            get
            {
                return this.pOIDField;
            }
            set
            {
                this.pOIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StyleNo
        {
            get
            {
                return this.styleNoField;
            }
            set
            {
                this.styleNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string POSupplier
        {
            get
            {
                return this.pOSupplierField;
            }
            set
            {
                this.pOSupplierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OLDPO
        {
            get
            {
                return this.oLDPOField;
            }
            set
            {
                this.oLDPOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HBLNumber
        {
            get
            {
                return this.hBLNumberField;
            }
            set
            {
                this.hBLNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shipper
        {
            get
            {
                return this.shipperField;
            }
            set
            {
                this.shipperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperCountry
        {
            get
            {
                return this.shipperCountryField;
            }
            set
            {
                this.shipperCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperAddress
        {
            get
            {
                return this.shipperAddressField;
            }
            set
            {
                this.shipperAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperPhoneNumber
        {
            get
            {
                return this.shipperPhoneNumberField;
            }
            set
            {
                this.shipperPhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NotifyParty
        {
            get
            {
                return this.notifyPartyField;
            }
            set
            {
                this.notifyPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MBLNumber
        {
            get
            {
                return this.mBLNumberField;
            }
            set
            {
                this.mBLNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceContract
        {
            get
            {
                return this.serviceContractField;
            }
            set
            {
                this.serviceContractField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContainerNumber
        {
            get
            {
                return this.containerNumberField;
            }
            set
            {
                this.containerNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContainerType
        {
            get
            {
                return this.containerTypeField;
            }
            set
            {
                this.containerTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CarrierSeal
        {
            get
            {
                return this.carrierSealField;
            }
            set
            {
                this.carrierSealField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperSeal
        {
            get
            {
                return this.shipperSealField;
            }
            set
            {
                this.shipperSealField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoadType
        {
            get
            {
                return this.loadTypeField;
            }
            set
            {
                this.loadTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntertraficInspection
        {
            get
            {
                return this.intertraficInspectionField;
            }
            set
            {
                this.intertraficInspectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InspectionIn
        {
            get
            {
                return this.inspectionInField;
            }
            set
            {
                this.inspectionInField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InspectionSupplier
        {
            get
            {
                return this.inspectionSupplierField;
            }
            set
            {
                this.inspectionSupplierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private MessageBLInfo[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageBLInfo")]
        public MessageBLInfo[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
