//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace BLXml.models.CmarBL
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Container
    {

        private ContainerCntr[] cntrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cntr", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContainerCntr[] Cntr
        {
            get
            {
                return this.cntrField;
            }
            set
            {
                this.cntrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ContainerCntr
    {

        private string cntr_noField;

        private string cntr_typeField;

        private string cntr_sealnoField;

        private string cntr_pcsField;

        private string cntr_uomField;

        private string cntr_weightField;

        private string cntr_cbmField;

        private string slnoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_no
        {
            get
            {
                return this.cntr_noField;
            }
            set
            {
                this.cntr_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_type
        {
            get
            {
                return this.cntr_typeField;
            }
            set
            {
                this.cntr_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_sealno
        {
            get
            {
                return this.cntr_sealnoField;
            }
            set
            {
                this.cntr_sealnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_pcs
        {
            get
            {
                return this.cntr_pcsField;
            }
            set
            {
                this.cntr_pcsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_uom
        {
            get
            {
                return this.cntr_uomField;
            }
            set
            {
                this.cntr_uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_weight
        {
            get
            {
                return this.cntr_weightField;
            }
            set
            {
                this.cntr_weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_cbm
        {
            get
            {
                return this.cntr_cbmField;
            }
            set
            {
                this.cntr_cbmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slno
        {
            get
            {
                return this.slnoField;
            }
            set
            {
                this.slnoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BillLadingMessage
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Container", typeof(Container))]
        [System.Xml.Serialization.XmlElementAttribute("Master", typeof(BillLadingMessageMaster), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("MessageInfo", typeof(BillLadingMessageMessageInfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMaster
    {

        private string mbl_noField;

        private string mbl_dateField;

        private string agent_codeField;

        private string agent_nameField;

        private string carrier_codeField;

        private string carrier_nameField;

        private string pol_codeField;

        private string pol_nameField;

        private string pol_etdField;

        private string pod_codeField;

        private string pod_nameField;

        private string pod_etaField;

        private string place_deliveryField;

        private string delivery_dateField;

        private string vesselField;

        private string voyageField;

        private string freight_statusField;

        private string shipment_termField;

        private string cntr_typeField;

        private string origin_country_nameField;

        private ContainerCntr[] containerField;

        private BillLadingMessageMasterHouseBillLadingHouse[] houseBillLadingField;

        private string refnoField;

        private string ref_dateField;

        private string branch_nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mbl_no
        {
            get
            {
                return this.mbl_noField;
            }
            set
            {
                this.mbl_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mbl_date
        {
            get
            {
                return this.mbl_dateField;
            }
            set
            {
                this.mbl_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agent_code
        {
            get
            {
                return this.agent_codeField;
            }
            set
            {
                this.agent_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agent_name
        {
            get
            {
                return this.agent_nameField;
            }
            set
            {
                this.agent_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier_code
        {
            get
            {
                return this.carrier_codeField;
            }
            set
            {
                this.carrier_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier_name
        {
            get
            {
                return this.carrier_nameField;
            }
            set
            {
                this.carrier_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pol_code
        {
            get
            {
                return this.pol_codeField;
            }
            set
            {
                this.pol_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pol_name
        {
            get
            {
                return this.pol_nameField;
            }
            set
            {
                this.pol_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pol_etd
        {
            get
            {
                return this.pol_etdField;
            }
            set
            {
                this.pol_etdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pod_code
        {
            get
            {
                return this.pod_codeField;
            }
            set
            {
                this.pod_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pod_name
        {
            get
            {
                return this.pod_nameField;
            }
            set
            {
                this.pod_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pod_eta
        {
            get
            {
                return this.pod_etaField;
            }
            set
            {
                this.pod_etaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string place_delivery
        {
            get
            {
                return this.place_deliveryField;
            }
            set
            {
                this.place_deliveryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string delivery_date
        {
            get
            {
                return this.delivery_dateField;
            }
            set
            {
                this.delivery_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vessel
        {
            get
            {
                return this.vesselField;
            }
            set
            {
                this.vesselField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string voyage
        {
            get
            {
                return this.voyageField;
            }
            set
            {
                this.voyageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string freight_status
        {
            get
            {
                return this.freight_statusField;
            }
            set
            {
                this.freight_statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipment_term
        {
            get
            {
                return this.shipment_termField;
            }
            set
            {
                this.shipment_termField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cntr_type
        {
            get
            {
                return this.cntr_typeField;
            }
            set
            {
                this.cntr_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin_country_name
        {
            get
            {
                return this.origin_country_nameField;
            }
            set
            {
                this.origin_country_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Cntr", typeof(ContainerCntr), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ContainerCntr[] Container
        {
            get
            {
                return this.containerField;
            }
            set
            {
                this.containerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("House", typeof(BillLadingMessageMasterHouseBillLadingHouse), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public BillLadingMessageMasterHouseBillLadingHouse[] HouseBillLading
        {
            get
            {
                return this.houseBillLadingField;
            }
            set
            {
                this.houseBillLadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refno
        {
            get
            {
                return this.refnoField;
            }
            set
            {
                this.refnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ref_date
        {
            get
            {
                return this.ref_dateField;
            }
            set
            {
                this.ref_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string branch_name
        {
            get
            {
                return this.branch_nameField;
            }
            set
            {
                this.branch_nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMasterHouseBillLadingHouse
    {

        private string shipper_codeField;

        private string shipper_nameField;

        private string shipper_add1Field;

        private string shipper_add2Field;

        private string shipper_add3Field;

        private string shipper_add4Field;

        private string shipper_add5Field;

        private string consignee_codeField;

        private string consignee_nameField;

        private string consignee_add1Field;

        private string consignee_add2Field;

        private string consignee_add3Field;

        private string consignee_add4Field;

        private string consignee_add5Field;

        private string notify_nameField;

        private string notify_add1Field;

        private string notify_add2Field;

        private string notify_add3Field;

        private string notify_add4Field;

        private string notify_add5Field;

        private string agent_codeField;

        private string agent_nameField;

        private string place_deliveryField;

        private string delivery_dateField;

        private string destination_placeField;

        private string destination_etaField;

        private string packagesField;

        private string uomField;

        private string commodityField;

        private string weightField;

        private string lbsField;

        private string cbmField;

        private string cftField;

        private string pcsField;

        private string freight_statusField;

        private string shipment_termField;

        private string shipment_typeField;

        private string ponoField;

        private string ams_filenoField;

        private string sub_house_noField;

        private string isf_noField;

        private string bl_reqField;

        private string remark1Field;

        private string remark2Field;

        private string remark3Field;

        private ContainerCntr[] containerField;

        private BillLadingMessageMasterHouseBillLadingHouseMarksNumbersMarksNumber[] marksNumbersField;

        private BillLadingMessageMasterHouseBillLadingHouseCargoDescriptionsCargoDescription[] cargoDescriptionsField;

        private string slnoField;

        private string house_noField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_code
        {
            get
            {
                return this.shipper_codeField;
            }
            set
            {
                this.shipper_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_name
        {
            get
            {
                return this.shipper_nameField;
            }
            set
            {
                this.shipper_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_add1
        {
            get
            {
                return this.shipper_add1Field;
            }
            set
            {
                this.shipper_add1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_add2
        {
            get
            {
                return this.shipper_add2Field;
            }
            set
            {
                this.shipper_add2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_add3
        {
            get
            {
                return this.shipper_add3Field;
            }
            set
            {
                this.shipper_add3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_add4
        {
            get
            {
                return this.shipper_add4Field;
            }
            set
            {
                this.shipper_add4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipper_add5
        {
            get
            {
                return this.shipper_add5Field;
            }
            set
            {
                this.shipper_add5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_code
        {
            get
            {
                return this.consignee_codeField;
            }
            set
            {
                this.consignee_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_name
        {
            get
            {
                return this.consignee_nameField;
            }
            set
            {
                this.consignee_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_add1
        {
            get
            {
                return this.consignee_add1Field;
            }
            set
            {
                this.consignee_add1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_add2
        {
            get
            {
                return this.consignee_add2Field;
            }
            set
            {
                this.consignee_add2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_add3
        {
            get
            {
                return this.consignee_add3Field;
            }
            set
            {
                this.consignee_add3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_add4
        {
            get
            {
                return this.consignee_add4Field;
            }
            set
            {
                this.consignee_add4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee_add5
        {
            get
            {
                return this.consignee_add5Field;
            }
            set
            {
                this.consignee_add5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_name
        {
            get
            {
                return this.notify_nameField;
            }
            set
            {
                this.notify_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_add1
        {
            get
            {
                return this.notify_add1Field;
            }
            set
            {
                this.notify_add1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_add2
        {
            get
            {
                return this.notify_add2Field;
            }
            set
            {
                this.notify_add2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_add3
        {
            get
            {
                return this.notify_add3Field;
            }
            set
            {
                this.notify_add3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_add4
        {
            get
            {
                return this.notify_add4Field;
            }
            set
            {
                this.notify_add4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notify_add5
        {
            get
            {
                return this.notify_add5Field;
            }
            set
            {
                this.notify_add5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agent_code
        {
            get
            {
                return this.agent_codeField;
            }
            set
            {
                this.agent_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agent_name
        {
            get
            {
                return this.agent_nameField;
            }
            set
            {
                this.agent_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string place_delivery
        {
            get
            {
                return this.place_deliveryField;
            }
            set
            {
                this.place_deliveryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string delivery_date
        {
            get
            {
                return this.delivery_dateField;
            }
            set
            {
                this.delivery_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination_place
        {
            get
            {
                return this.destination_placeField;
            }
            set
            {
                this.destination_placeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination_eta
        {
            get
            {
                return this.destination_etaField;
            }
            set
            {
                this.destination_etaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string packages
        {
            get
            {
                return this.packagesField;
            }
            set
            {
                this.packagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uom
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commodity
        {
            get
            {
                return this.commodityField;
            }
            set
            {
                this.commodityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lbs
        {
            get
            {
                return this.lbsField;
            }
            set
            {
                this.lbsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cbm
        {
            get
            {
                return this.cbmField;
            }
            set
            {
                this.cbmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cft
        {
            get
            {
                return this.cftField;
            }
            set
            {
                this.cftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pcs
        {
            get
            {
                return this.pcsField;
            }
            set
            {
                this.pcsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string freight_status
        {
            get
            {
                return this.freight_statusField;
            }
            set
            {
                this.freight_statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipment_term
        {
            get
            {
                return this.shipment_termField;
            }
            set
            {
                this.shipment_termField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipment_type
        {
            get
            {
                return this.shipment_typeField;
            }
            set
            {
                this.shipment_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pono
        {
            get
            {
                return this.ponoField;
            }
            set
            {
                this.ponoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ams_fileno
        {
            get
            {
                return this.ams_filenoField;
            }
            set
            {
                this.ams_filenoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sub_house_no
        {
            get
            {
                return this.sub_house_noField;
            }
            set
            {
                this.sub_house_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isf_no
        {
            get
            {
                return this.isf_noField;
            }
            set
            {
                this.isf_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bl_req
        {
            get
            {
                return this.bl_reqField;
            }
            set
            {
                this.bl_reqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark1
        {
            get
            {
                return this.remark1Field;
            }
            set
            {
                this.remark1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark2
        {
            get
            {
                return this.remark2Field;
            }
            set
            {
                this.remark2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark3
        {
            get
            {
                return this.remark3Field;
            }
            set
            {
                this.remark3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Cntr", typeof(ContainerCntr), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ContainerCntr[] Container
        {
            get
            {
                return this.containerField;
            }
            set
            {
                this.containerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MarksNumber", typeof(BillLadingMessageMasterHouseBillLadingHouseMarksNumbersMarksNumber), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public BillLadingMessageMasterHouseBillLadingHouseMarksNumbersMarksNumber[] MarksNumbers
        {
            get
            {
                return this.marksNumbersField;
            }
            set
            {
                this.marksNumbersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CargoDescription", typeof(BillLadingMessageMasterHouseBillLadingHouseCargoDescriptionsCargoDescription), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public BillLadingMessageMasterHouseBillLadingHouseCargoDescriptionsCargoDescription[] CargoDescriptions
        {
            get
            {
                return this.cargoDescriptionsField;
            }
            set
            {
                this.cargoDescriptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string slno
        {
            get
            {
                return this.slnoField;
            }
            set
            {
                this.slnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string house_no
        {
            get
            {
                return this.house_noField;
            }
            set
            {
                this.house_noField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMasterHouseBillLadingHouseMarksNumbersMarksNumber
    {

        private string rownumField;

        private string cargo_marksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rownum
        {
            get
            {
                return this.rownumField;
            }
            set
            {
                this.rownumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cargo_marks
        {
            get
            {
                return this.cargo_marksField;
            }
            set
            {
                this.cargo_marksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMasterHouseBillLadingHouseCargoDescriptionsCargoDescription
    {

        private string rownumField;

        private string cargo_descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rownum
        {
            get
            {
                return this.rownumField;
            }
            set
            {
                this.rownumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cargo_description
        {
            get
            {
                return this.cargo_descriptionField;
            }
            set
            {
                this.cargo_descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BillLadingMessageMessageInfo
    {

        private string messagesenderField;

        private string messagenumberField;

        private string messagedateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messagesender
        {
            get
            {
                return this.messagesenderField;
            }
            set
            {
                this.messagesenderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messagenumber
        {
            get
            {
                return this.messagenumberField;
            }
            set
            {
                this.messagenumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mesagedates
        {
            get
            {
                return this.messagedateField;
            }
            set
            {
                this.messagedateField = value;
            }
        }
    }
}